export const PERMISSION_ROUTES: Record<string, string | string[]> = {
  '/dashboard':        'dashboard:read',
  '/products':         'products:read',
  '/products/new':     'products:create',
  '/categories':       'categories:read',
  '/warehouses':       'warehouses:read',
  '/stock':            'stock:read',
  '/movements':        'stock:read',
  '/sales':            'sales:read',
  '/sales/new':        'sales:create',
  '/purchases':        'purchases:read',
  '/transfers':        'transfers:read',
  '/adjustments':      'adjustments:read',
  '/returns':          'returns:read',
  '/suppliers':        'suppliers:read',
  '/customers':        'customers:read',
  '/users':            'users:read',
  '/roles':            'roles:read',
  '/currencies':       'currencies:read',
  '/exchange-rates':   'exchange_rates:read',
  '/settings':         'settings:read',
  '/reports':          'reports:read',
  '/audit-logs':       'audit:read',
  '/import':           'imports:create',
  '/export':           'exports:read',
  '/debts':            'finance:read',
  '/sync/incidents':   'settings:read',
};
