import {
  Add,
  AddPhotoAlternate,
  ArrowBack,
  ArrowForward,
  AttachMoney,
  Block,
  Cancel,
  Check,
  CheckCircle,
  Checklist,
  ChevronLeft,
  ChevronRight,
  Close,
  CloudOff,
  ContentCopy,
  CreditCard,
  Delete,
  Description,
  DoneAll,
  Download,
  Edit,
  Error,
  FilterList,
  Fullscreen,
  Group,
  History,
  Image,
  Inventory,
  KeyboardArrowDown,
  KeyboardArrowUp,
  LocationOn,
  Map,
  MyLocation,
  Notifications,
  OpenInNew,
  Percent,
  PowerSettingsNew,
  RadioButtonUnchecked,
  Refresh,
  Save,
  Schedule,
  Search,
  Send,
  Settings,
  Share,
  ShoppingCart,
  SignalCellularAlt,
  Star,
  Storage,
  Sync,
  ToggleOff,
  TrendingDown,
  TrendingUp,
  LocalShipping,
  Upload,
  Verified,
  Visibility,
  VisibilityOff,
  VpnKey,
  Warehouse,
  Warning,
  Wifi,
  WifiOff,
  ZoomIn,
  ZoomOut,
} from '@material-symbols-svg/react';

export type SvgIcon = typeof Close;

export {
  Add as Plus,
  AddPhotoAlternate as ImagePlus,
  ArrowBack as ArrowLeft,
  ArrowForward as ArrowRight,
  Block as Ban,
  Cancel as XCircle,
  Check,
  CheckCircle,
  Checklist as PackageCheck,
  ChevronLeft,
  ChevronRight,
  Close as X,
  CloudOff,
  ContentCopy as Copy,
  CreditCard,
  Delete as Trash2,
  Description as FileText,
  DoneAll as CheckCheck,
  Download,
  Edit as Pencil,
  Error as AlertCircle,
  FilterList as Filter,
  Fullscreen as Maximize2,
  Group as Users,
  History as HistoryToggle,
  Image,
  Inventory as Package,
  KeyboardArrowDown as ChevronDown,
  KeyboardArrowUp as ChevronUp,
  LocalShipping as Truck,
  LocationOn as MapPin,
  Map as MapIcon,
  MyLocation as Crosshair,
  Notifications as Bell,
  OpenInNew as ExternalLink,
  PowerSettingsNew as Power,
  RadioButtonUnchecked as CircleOff,
  Refresh as RefreshCw,
  Save,
  Schedule as Clock,
  Search,
  Send,
  Settings,
  Share,
  ShoppingCart,
  SignalCellularAlt as Signal,
  Star,
  Storage as HardDrive,
  Sync as Loader2,
  ToggleOff as ToggleLeft,
  TrendingDown,
  TrendingUp,
  AttachMoney as DollarSign,
  Percent,
  Upload,
  Verified as CheckCircle2,
  Visibility as Eye,
  VisibilityOff as EyeOff,
  VpnKey as KeyRound,
  Warehouse,
  Warning as AlertTriangle,
  Wifi,
  WifiOff,
  ZoomIn,
  ZoomOut,
};

export function Sparkles(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      {...props}
    >
      <path d="M12 3l1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5z" />
      <path d="M18 15l1 2.5L21.5 18l-2.5 1L18 21.5 16.5 19 14 18l2.5-1z" />
    </svg>
  );
}
